servers=[
   {
    :hostname => "ES",
    :ip => "192.168.56.110",
    :ram => 3024,
    :cpu => 2
  },
  {
    :hostname => "logstash",
    :ip => "192.168.56.111",
    :ram => 512,
    :cpu => 1
},
  {
    :hostname => "target",
    :ip => "192.168.56.112",
    :ram => 512,
    :cpu => 1
}

]


Vagrant.configure("2") do |config|

   servers.each do |machine|
    
       
    config.vm.define machine[:hostname] do |node|
        
        node.vm.box = "bento/ubuntu-20.04"
        node.vm.hostname = machine[:hostname]
        node.vm.network "private_network",  ip: machine[:ip]
        node.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            vb.customize ["modifyvm", :id, "--cpus", machine[:cpu]]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            vb.customize ["modifyvm", :id, "--name", machine[:hostname]]
        end
        # if machine[:hostname] == "ES"
        #   node.vm.provision :shell, :path => "install_es.sh"
        #   node.vm.provision :shell, :path => "install_logstash.sh"
        #   node.vm.provision :shell, :path => "install_kibana.sh"
        # end
        

        
    end

    

  end
  

end
