servers=[
  # {
  #   :hostname => "ans-controller",
  #   :ip => "192.168.56.110",
  #   :type => "controller",
  #   :ram => 1024,
  #   :cpu => 1
  # },
   {
    :hostname => "ans1",
    :ip => "192.168.56.110",
    :type => "target",
    :ram => 512,
    :cpu => 1
  },
  {
    :hostname => "ans2",
    :ip => "192.168.56.111",
    :type => "target",
    :ram => 512,
    :cpu => 1
}

]


Vagrant.configure("2") do |config|

   servers.each do |machine|
    
       
    config.vm.define machine[:hostname] do |node|
        
        node.vm.box = "bento/ubuntu-20.04"
        node.vm.hostname = machine[:hostname]
        node.vm.network "private_network",  ip: machine[:ip]
        node.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            vb.customize ["modifyvm", :id, "--cpus", machine[:cpu]]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            vb.customize ["modifyvm", :id, "--name", machine[:hostname]]
        end
        # if machine[:type] == 'controller'
        #   node.vm.provision :shell, :path => "configure_controller.sh"
        #     end
        

        
    end

    

  end
  

end
